"""wa lifecycle columns

Revision ID: 21a044eb1c0a
Revises: 0001
Create Date: 2026-05-03 11:47:02.686930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '21a044eb1c0a'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('leads_phone_key', 'leads', type_='unique')
    op.drop_index('ix_leads_phone', table_name='leads')
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=True)
    op.alter_column('rm_handoffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('whatsapp_messages', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('read_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_messages', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('whatsapp_messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whatsapp_messages', 'sent_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('whatsapp_messages', 'replied_at')
    op.drop_column('whatsapp_messages', 'read_at')
    op.drop_column('whatsapp_messages', 'delivered_at')
    op.alter_column('rm_handoffs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.create_index('ix_leads_phone', 'leads', ['phone'], unique=False)
    op.create_unique_constraint('leads_phone_key', 'leads', ['phone'])
    op.alter_column('leads', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('leads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('calls', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
