"""add audio_path and next_call_at

Revision ID: 2d16ded51575
Revises: 10431e09a0b8
Create Date: 2026-05-06 19:04:30.174457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2d16ded51575'
down_revision: Union[str, None] = '10431e09a0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('audio_path', sa.String(length=500), nullable=True))
    op.add_column('leads', sa.Column('next_call_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'next_call_at')
    op.drop_column('calls', 'audio_path')
    # ### end Alembic commands ###
