"""add email to lead + email_messages table

Revision ID: a75f3a2d4ce3
Revises: 2d16ded51575
Create Date: 2026-05-15 12:46:25.046452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a75f3a2d4ce3'
down_revision: Union[str, None] = '2d16ded51575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('call_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('to_email', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id')
    )
    op.add_column('leads', sa.Column('email', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_column('leads', 'email')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
